# Generated by Django 4.2.3 on 2023-07-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("premier_league", "0002_alter_team_stadium"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("guid", models.CharField(max_length=36, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("shortname", models.CharField(max_length=50, null=True)),
                ("description", models.TextField()),
                ("team", models.CharField(max_length=50, null=True)),
                ("author", models.CharField(max_length=50, null=True)),
                ("guid", models.CharField(max_length=36, unique=True)),
            ],
        ),
    ]
