# Generated by Django 4.2.3 on 2023-07-17 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("premier_league", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="stadium",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team",
                to="premier_league.stadium",
            ),
        ),
    ]
