# Generated by Django 4.2.3 on 2023-07-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("premier_league", "0006_user_teams"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField()),
                ("guid", models.CharField(max_length=36, unique=True)),
            ],
        ),
    ]
